// <auto-generated />
using System;
using HotelProjeto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelProjeto.Migrations
{
    [DbContext(typeof(HotelProjetoContext))]
    [Migration("20240127150352_CreateDatabase")]
    partial class CreateDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HotelProjeto.Cargo", b =>
                {
                    b.Property<int>("codCargo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("codCargo"));

                    b.Property<string>("nomeCargo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("codCargo");

                    b.ToTable("Cargo");
                });

            modelBuilder.Entity("HotelProjeto.Cliente", b =>
                {
                    b.Property<int>("codCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("codCliente"));

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nacionalidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("telefone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("codCliente");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("HotelProjeto.ConsumoRestauranteFrigobar", b =>
                {
                    b.Property<int>("codConsumo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("codConsumo"));

                    b.Property<string>("descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("numeroConta1")
                        .HasColumnType("int");

                    b.Property<bool>("restauranteEntregaQuarto")
                        .HasColumnType("bit");

                    b.Property<double>("valor")
                        .HasColumnType("float");

                    b.HasKey("codConsumo");

                    b.HasIndex("numeroConta1");

                    b.ToTable("ConsumoRestauranteFrigobar");
                });

            modelBuilder.Entity("HotelProjeto.Conta", b =>
                {
                    b.Property<int>("numeroConta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("numeroConta"));

                    b.Property<int?>("codCliente1")
                        .HasColumnType("int");

                    b.Property<double>("valorTotal")
                        .HasColumnType("float");

                    b.HasKey("numeroConta");

                    b.HasIndex("codCliente1");

                    b.ToTable("Conta");
                });

            modelBuilder.Entity("HotelProjeto.Endereco", b =>
                {
                    b.Property<int>("codEndereco")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("codEndereco"));

                    b.Property<string>("bairro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("numero")
                        .HasColumnType("int");

                    b.Property<string>("rua")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("codEndereco");

                    b.ToTable("Endereco");
                });

            modelBuilder.Entity("HotelProjeto.Filial", b =>
                {
                    b.Property<int>("codFilial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("codFilial"));

                    b.Property<int?>("codEndereco1")
                        .HasColumnType("int");

                    b.Property<string>("nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("numeroQuartoCasal")
                        .HasColumnType("int");

                    b.Property<int>("numeroQuartoFamilia")
                        .HasColumnType("int");

                    b.Property<int>("numeroQuartoPresidencial")
                        .HasColumnType("int");

                    b.Property<int>("numeroQuartoSolteiro")
                        .HasColumnType("int");

                    b.Property<int>("quantidadeEstrelas")
                        .HasColumnType("int");

                    b.Property<double>("valorQuartoCasal")
                        .HasColumnType("float");

                    b.Property<double>("valorQuartoFamilia")
                        .HasColumnType("float");

                    b.Property<double>("valorQuartoPresidencial")
                        .HasColumnType("float");

                    b.Property<double>("valorQuartoSolteiro")
                        .HasColumnType("float");

                    b.HasKey("codFilial");

                    b.HasIndex("codEndereco1");

                    b.ToTable("Filial");
                });

            modelBuilder.Entity("HotelProjeto.FormaPagamento", b =>
                {
                    b.Property<int>("codForma")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("codForma"));

                    b.Property<string>("forma")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("codForma");

                    b.ToTable("FormaPagamento");
                });

            modelBuilder.Entity("HotelProjeto.Funcionario", b =>
                {
                    b.Property<int>("codFuncionario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("codFuncionario"));

                    b.Property<int?>("codCargo1")
                        .HasColumnType("int");

                    b.Property<string>("nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("codFuncionario");

                    b.HasIndex("codCargo1");

                    b.ToTable("Funcionario");
                });

            modelBuilder.Entity("HotelProjeto.Pagamento", b =>
                {
                    b.Property<int>("codPagamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("codPagamento"));

                    b.Property<int?>("codForma1")
                        .HasColumnType("int");

                    b.Property<int?>("numeroConta1")
                        .HasColumnType("int");

                    b.HasKey("codPagamento");

                    b.HasIndex("codForma1");

                    b.HasIndex("numeroConta1");

                    b.ToTable("Pagamento");
                });

            modelBuilder.Entity("HotelProjeto.Quarto", b =>
                {
                    b.Property<int>("numeroQuarto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("numeroQuarto"));

                    b.Property<int?>("codTipoQuartocodTipo")
                        .HasColumnType("int");

                    b.Property<double>("valorQuarto")
                        .HasColumnType("float");

                    b.HasKey("numeroQuarto");

                    b.HasIndex("codTipoQuartocodTipo");

                    b.ToTable("Quarto");
                });

            modelBuilder.Entity("HotelProjeto.Reserva", b =>
                {
                    b.Property<int>("codReserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("codReserva"));

                    b.Property<int?>("codCliente1")
                        .HasColumnType("int");

                    b.Property<int?>("codFuncionario1")
                        .HasColumnType("int");

                    b.Property<DateOnly>("dataCheckin")
                        .HasColumnType("date");

                    b.Property<DateOnly>("dataCheckout")
                        .HasColumnType("date");

                    b.Property<int?>("numeroQuarto1")
                        .HasColumnType("int");

                    b.HasKey("codReserva");

                    b.HasIndex("codCliente1");

                    b.HasIndex("codFuncionario1");

                    b.HasIndex("numeroQuarto1");

                    b.ToTable("Reserva");
                });

            modelBuilder.Entity("HotelProjeto.ServicoLavanderia", b =>
                {
                    b.Property<int>("codServico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("codServico"));

                    b.Property<int?>("codTipoServico1")
                        .HasColumnType("int");

                    b.Property<int?>("numeroConta1")
                        .HasColumnType("int");

                    b.HasKey("codServico");

                    b.HasIndex("codTipoServico1");

                    b.HasIndex("numeroConta1");

                    b.ToTable("ServicoLavanderia");
                });

            modelBuilder.Entity("HotelProjeto.TipoQuarto", b =>
                {
                    b.Property<int>("codTipo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("codTipo"));

                    b.Property<bool>("capacidadeOpcional")
                        .HasColumnType("bit");

                    b.Property<int>("capcidadeMaxima")
                        .HasColumnType("int");

                    b.Property<string>("tipo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("codTipo");

                    b.ToTable("TipoQuarto");
                });

            modelBuilder.Entity("HotelProjeto.TipoServicoLavanderia", b =>
                {
                    b.Property<int>("codTipoServico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("codTipoServico"));

                    b.Property<string>("servico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("valor")
                        .HasColumnType("float");

                    b.HasKey("codTipoServico");

                    b.ToTable("TipoServicoLavanderia");
                });

            modelBuilder.Entity("HotelProjeto.ConsumoRestauranteFrigobar", b =>
                {
                    b.HasOne("HotelProjeto.Conta", "numeroConta")
                        .WithMany()
                        .HasForeignKey("numeroConta1");

                    b.Navigation("numeroConta");
                });

            modelBuilder.Entity("HotelProjeto.Conta", b =>
                {
                    b.HasOne("HotelProjeto.Cliente", "codCliente")
                        .WithMany()
                        .HasForeignKey("codCliente1");

                    b.Navigation("codCliente");
                });

            modelBuilder.Entity("HotelProjeto.Filial", b =>
                {
                    b.HasOne("HotelProjeto.Endereco", "codEndereco")
                        .WithMany()
                        .HasForeignKey("codEndereco1");

                    b.Navigation("codEndereco");
                });

            modelBuilder.Entity("HotelProjeto.Funcionario", b =>
                {
                    b.HasOne("HotelProjeto.Cargo", "codCargo")
                        .WithMany()
                        .HasForeignKey("codCargo1");

                    b.Navigation("codCargo");
                });

            modelBuilder.Entity("HotelProjeto.Pagamento", b =>
                {
                    b.HasOne("HotelProjeto.FormaPagamento", "codForma")
                        .WithMany()
                        .HasForeignKey("codForma1");

                    b.HasOne("HotelProjeto.Conta", "numeroConta")
                        .WithMany()
                        .HasForeignKey("numeroConta1");

                    b.Navigation("codForma");

                    b.Navigation("numeroConta");
                });

            modelBuilder.Entity("HotelProjeto.Quarto", b =>
                {
                    b.HasOne("HotelProjeto.TipoQuarto", "codTipoQuarto")
                        .WithMany()
                        .HasForeignKey("codTipoQuartocodTipo");

                    b.Navigation("codTipoQuarto");
                });

            modelBuilder.Entity("HotelProjeto.Reserva", b =>
                {
                    b.HasOne("HotelProjeto.Cliente", "codCliente")
                        .WithMany()
                        .HasForeignKey("codCliente1");

                    b.HasOne("HotelProjeto.Funcionario", "codFuncionario")
                        .WithMany()
                        .HasForeignKey("codFuncionario1");

                    b.HasOne("HotelProjeto.Quarto", "numeroQuarto")
                        .WithMany()
                        .HasForeignKey("numeroQuarto1");

                    b.Navigation("codCliente");

                    b.Navigation("codFuncionario");

                    b.Navigation("numeroQuarto");
                });

            modelBuilder.Entity("HotelProjeto.ServicoLavanderia", b =>
                {
                    b.HasOne("HotelProjeto.TipoServicoLavanderia", "codTipoServico")
                        .WithMany()
                        .HasForeignKey("codTipoServico1");

                    b.HasOne("HotelProjeto.Conta", "numeroConta")
                        .WithMany()
                        .HasForeignKey("numeroConta1");

                    b.Navigation("codTipoServico");

                    b.Navigation("numeroConta");
                });
#pragma warning restore 612, 618
        }
    }
}
